name: Website Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check websites
        run: curl -X POST "${{ secrets.APP_URL }}/api/monitor/check" -H "Content-Type: application/json" -d "{\"secret\":\"${{ secrets.CRON_SECRET }}\"}"
