name: Website Monitor
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST "${{ secrets.APP_URL }}/api/monitor/check" -H "Content-Type: application/json" -d '{"secret":"${{ secrets.CRON_SECRET }}"}'
